# Change these first
owner: kacty # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Kactus
    url: https://www.kactus.com
    icon: https://www.kactus.com/favicon-16x16.png
    # le response time par défaut est de 30 secs avant de déclenché un mode dégradé
    #maxResponseTime: 5000
    
status-website:
  #cname: status.kactus.com
  favicon: https://www.kactus.com/favicon-16x16.png
  baseUrl: /uptime # where "repo" is your repository name
  logoUrl: https://www.kactus.com/assets/logos/kactus/only-logo-49339dc1e6ddaaaf34089190d4430e5532d132017d25c6f2a4e19a793648b5b9.png
  name: Kactus
  introTitle: Status page
  navbar:
    - title: Status
      href: /
    - title: Kactus
      href: https://www.kactus.com
  theme: light

  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

